### ISSUE TITLE
Why not Beremiz instead?

### ISSUE THREAD

**Issue by TheColonel2688** [r2k-in-the-vortex/ExamplePrjForRustyIntegration#1]
I have just recently learned that OpenPLC is actually a fork of Beremiz, with reduced functionality. 

it is also pretty clear that up until recently the  "Creator" of OpenPLC has been trying to pass off OpenPLC as entirely an original work, and only recently started mentioning Beremiz at all because he was forced too. 

he seems like a sketchy guy.

**Comment by r2k-in-the-vortex** [comment]
And Beremiz is built on top of MatIEC compiler written by a guy from Portugal completely separate from the Beremiz crew. That's the beauty of open source, you don't have to reinvent the bicycle yourself, you can simply reuse and repurpose the work done before you.

I haven't really dug through all of Beremiz codebase, but the best I can understand in their runtime they do all plc comms though python, which doesn't really suit my purposes. That's an important difference in how OpenPLC works, there the entire runtime is compiled. I think the original motivation was so it could run on hardware platforms that can't run python, but it also has importance for real time performance which is what interests me.

Anyway, my idea of taking rusty compiler to use bypasses the use of PLCopen editor and MatIEC compiler entirely. VS code or any other code editor works just fine for ST (and I personally don't care about the other 61311-3 languages). And MatIEC compiler... until quite recently it's been the only open source offering, but it's dated and it's not in active development, it'll never catch up to 3rd edition of the IEC standard. And iec2c translation.... yeah there are limits there.

Anyway, so this what I'm aiming to do here and why I'm doing it for OpenPLC not Beremiz. Of course, if you wish to do the same compiler swap for Beremiz, all the power to you, have at it.

**Comment by TheColonel2688** [comment]
the issue wasn't the fork, it was that for a long time he acted like it wasn't a fork. 
he didn't make any accreditation any where that made it obvious it was a fork and what jt was a fork of.

you make a good point with the runtime though.

**Comment by r2k-in-the-vortex** [comment]
I don't really care about this sort of drama. Code is code, I care about what I write and if and how it works, who wrote some other code and who is claiming credit for it is concern for someone else.
